In [3]:
import math


In [4]:
math.sqrt(25)

5.0

math.pi

In [5]:
math.pi

3.141592653589793

In [6]:
import math as mt

In [7]:
mt.sqrt(25)

5.0

In [8]:
import numpy as np
import math as mt
from scipy import stats

In [9]:
from numpy import random

In [11]:
# uniform random numbers in [0,1]
dataOne = random.rand(5,5)

In [12]:
print(dataOne)

[[0.4477726  0.39189444 0.23095322 0.01680433 0.61117604]
 [0.40880067 0.34524795 0.39380909 0.18950835 0.62536479]
 [0.99631513 0.74063833 0.6344099  0.00460403 0.03530089]
 [0.46213114 0.62319372 0.39479433 0.69379425 0.12965623]
 [0.02354618 0.20767622 0.56812844 0.85561829 0.35923748]]


In [13]:
np.mean(dataOne)

0.4156150415195776

In [14]:
print('I Love data Science')

I Love data Science


In [15]:
variableName = 25
variableName1 = 'I Love data Science'
print(variableName1)

I Love data Science


In [16]:
type(variableName1)

str

In [17]:
type(variableName)

int

In [18]:
variableName2 = 25.0
type(variableName2)

float

In [19]:
varOne = 25
varTwo = 25.0
varThree = varOne + varTwo
print(varThree)

50.0


In [20]:
type(varThree)

float

In [22]:
varOne = 25
varTwo = 'Hello'
varThree = varOne + varTwo
print(varThree)


TypeError: unsupported operand type(s) for +: 'int' and 'str'

In [24]:
#  Cast int to str, using function str
#other types of cast are int() , float()
varOne = str(25)
varTwo = 'Hello'
varThree = varOne + varTwo
print(varThree)

25Hello


In [25]:
#Lists
listOne = [1,2,3,4]

In [26]:
print(listOne[1:3])

[2, 3]


In [27]:
print(listOne[0:3])

[1, 2, 3]


In [28]:
#Dictionaries
tel = {'jack': 4098, 'sape': 4139}

In [29]:
tel['jack']

4098

In [65]:
#Practice
iDictionary = {'nInt1': 10, 'nInt2': 20,'nInt3': 30,'nInt4': 40,'nInt5': 50}


In [66]:
#Return e raised to the power x, where e = 2.718281… is the base of natural logarithms
mt.exp(iDictionary['nInt1'])

22026.465794806718

math.pow(3, iDictionary['nInt2'])

In [67]:
#Return x raised to the power y
mt.pow(3, iDictionary['nInt1'])

59049.0

In [69]:
#Return an accurate floating point sum of values in the iterable
iDictionary.values()
mt.fsum(iDictionary.values())


150.0

In [74]:
#Return the greatest common divisor of the integers a and b.
mt.gcd(iDictionary['nInt1'],iDictionary['nInt5'] )

10

In [75]:
#Return True if x is a positive or negative infinity, and False otherwise.
mt.isinf(-iDictionary['nInt5'])

False

In [81]:
#Return the sine of x radians.
mt.sin(iDictionary['nInt1'])

-0.5440211108893698